[package]
name = "conrod-testing"
version = "0.1.0"
authors = ["Dabo Ross <daboross@daboross.net>"]
description = "Personal testbed of conrod."

repository = "https://github.com/daboross/conrod-testing"

readme = "README.md"

keywords = []
categories = ["games"]
license = "MIT"

[lib]
name = "conrod_testing"
path = "src/rust/lib.rs"

[dependencies]
# Graphics
glium = "0.16"
glutin = "0.7"
rusttype = "0.2"
# now below:
# conrod = { version = "0.51", features = ["glium", "winit"] }
# Networking
hyper = "0.10"
hyper-rustls = "0.3"
screeps-api = { git = "https://github.com/daboross/rust-screeps-api.git" }
# Logging
time = "0.1"
log = "0.3"
fern = "0.3"
clap = "2.22"

[dependencies.conrod]
# waiting on my finishing https://github.com/PistonDevelopers/conrod/pull/964
git = "https://github.com/daboross/conrod.git"
branch = "add-password-text-boxes"
features = ["glium", "winit"]

[[bin]]
name = "testbed"
doc = false
