max_width = 120
ideal_width = 110
fn_single_line = false
fn_args_paren_newline = false
report_fixme = "unnumbered"
use_try_shorthand = true
write_mode = "overwrite"
condense_wildcard_suffices = true
closure_block_indent_threshold = 1
